baseURL = "https://biodivgame.github.io"
languageCode = "en-US"
title = "Biodiversity game!"
publishDir = "docs"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/arboretum_mini.jpg"
  author = "BI2098 - EiT Group 1"
  description = "We made a small website for our QR-code game at Ringve Botanical Garden in Trondheim."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "biodivgame"
  Email         = "email@example.com"

## Main Menu
[[menu.main]]
  name = "archive"
  weight = 100
  identifier = "archive"
  url = "/archive/"

